name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress --no-suggest
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install NPM dependencies
              run: npm install
            - name: Run PHP CodeSniffer
              run: vendor/bin/phpcs --standard=phpcs.xml.dist src/
            - name: Run PHPUnit
              run: vendor/bin/phpunit --configuration phpunit.xml.dist
            - name: Run JS Lint
              run: npm run lint --if-present
