name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress --no-suggest
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install NPM dependencies
              run: npm install
            - name: Build assets
              run: npm run build --if-present
            - name: Run tests
              run: vendor/bin/phpunit --configuration phpunit.xml.dist
            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      plugin.php
                      block.json
                      src/**
                      assets/**
                      composer.json
                      package.json
                      CHANGELOG.md
                      README.md
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
